"""create study catalogue

Revision ID: fb2a9c3899d5
Revises:
Create Date: 2026-08-14 08:50:44.063623

Creates the fourteen catalogue tables with their foreign keys, natural-key
unique constraints and query indexes. Verified in both directions against a
SQLite file (``alembic upgrade head`` then ``alembic downgrade base``).

Constructs that behave differently on SQLite than on PostgreSQL:

* ``JSON_VARIANT`` is ``JSONB`` on PostgreSQL and ``JSON`` (stored as text) on
  SQLite. Only PostgreSQL can index or query inside the payload.
* ``sa.Enum(..., native_enum=False)`` becomes ``VARCHAR(32)`` plus a ``CHECK``
  constraint on both dialects, deliberately avoiding a native PostgreSQL enum
  type that would need its own migration whenever a status is added.
* ``sa.BigInteger`` is a 64-bit column on PostgreSQL and an ordinary dynamically
  typed ``INTEGER`` on SQLite, which is also 64-bit; no practical difference.
* ``ondelete`` clauses are only enforced by SQLite when
  ``PRAGMA foreign_keys=ON`` is set, which the engine factory in
  ``perp_lab.catalog.session`` does on every connection.
* Index and constraint changes are wrapped in ``batch_alter_table`` because
  SQLite cannot ``ALTER`` in place; this is a no-op on PostgreSQL.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from perp_lab.catalog.models import JSON_VARIANT

# revision identifiers, used by Alembic.
revision: str = "fb2a9c3899d5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "studies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("primary_symbol", sa.String(length=32), nullable=False),
        sa.Column("secondary_symbol", sa.String(length=32), nullable=True),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("holdout_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("holdout_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_studies_key"),
    )
    op.create_table(
        "experiment_rounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("criterion", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "EXECUTED",
                "AUDITED",
                "REJECTED",
                "INVALIDATED",
                "SKIPPED",
                "NOT_EXECUTED",
                "NOT_AVAILABLE",
                "HOLDOUT_LOCKED",
                name="result_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("source_artifact", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_id", "key", name="uq_experiment_rounds_study_key"),
    )
    with op.batch_alter_table("experiment_rounds", schema=None) as batch_op:
        batch_op.create_index("ix_experiment_rounds_key", ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_experiment_rounds_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_experiment_rounds_study_id"), ["study_id"], unique=False
        )

    op.create_table(
        "holdout_registry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("candidate_key", sa.String(length=191), nullable=False),
        sa.Column("candidate_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("authorization_token_present", sa.Boolean(), nullable=False),
        sa.Column("authorization_recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("commit_before", sa.String(length=40), nullable=True),
        sa.Column("commit_after", sa.String(length=40), nullable=True),
        sa.Column("dataset_sha256", sa.String(length=64), nullable=True),
        sa.Column("command", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("audited", sa.Boolean(), nullable=False),
        sa.Column("audited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("auditor", sa.String(length=128), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "EXECUTED",
                "AUDITED",
                "REJECTED",
                "INVALIDATED",
                "SKIPPED",
                "NOT_EXECUTED",
                "NOT_AVAILABLE",
                "HOLDOUT_LOCKED",
                name="result_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("source_artifact", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "audited = false OR opened_at IS NOT NULL",
            name="ck_holdout_registry_audited_implies_opened",
        ),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_id", "candidate_key", name="uq_holdout_registry_natural_key"),
    )
    with op.batch_alter_table("holdout_registry", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_holdout_registry_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_holdout_registry_study_id"), ["study_id"], unique=False
        )

    op.create_table(
        "metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("scope_ref", sa.String(length=191), nullable=False),
        sa.Column("metric_key", sa.String(length=96), nullable=False),
        sa.Column("value", sa.Double(), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("context", JSON_VARIANT, nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "EXECUTED",
                "AUDITED",
                "REJECTED",
                "INVALIDATED",
                "SKIPPED",
                "NOT_EXECUTED",
                "NOT_AVAILABLE",
                "HOLDOUT_LOCKED",
                name="result_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("source_artifact", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "study_id", "scope", "scope_ref", "metric_key", name="uq_metrics_natural_key"
        ),
    )
    with op.batch_alter_table("metrics", schema=None) as batch_op:
        batch_op.create_index("ix_metrics_key", ["metric_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_metrics_scope"), ["scope"], unique=False)
        batch_op.create_index(batch_op.f("ix_metrics_scope_ref"), ["scope_ref"], unique=False)
        batch_op.create_index(batch_op.f("ix_metrics_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_metrics_study_id"), ["study_id"], unique=False)

    op.create_table(
        "strategy_families",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=True),
        sa.Column("module", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "EXECUTED",
                "AUDITED",
                "REJECTED",
                "INVALIDATED",
                "SKIPPED",
                "NOT_EXECUTED",
                "NOT_AVAILABLE",
                "HOLDOUT_LOCKED",
                name="result_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("source_artifact", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_id", "key", name="uq_strategy_families_study_key"),
    )
    with op.batch_alter_table("strategy_families", schema=None) as batch_op:
        batch_op.create_index("ix_strategy_families_key", ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_strategy_families_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_strategy_families_study_id"), ["study_id"], unique=False
        )

    op.create_table(
        "gate_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("criterion_key", sa.String(length=96), nullable=False),
        sa.Column("criterion", sa.Text(), nullable=True),
        sa.Column("verdict", sa.String(length=24), nullable=False),
        sa.Column("observed", sa.Double(), nullable=True),
        sa.Column("threshold", sa.Double(), nullable=True),
        sa.Column("n_seeds_passed", sa.Integer(), nullable=True),
        sa.Column("n_seeds_total", sa.Integer(), nullable=True),
        sa.Column("detail", JSON_VARIANT, nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "EXECUTED",
                "AUDITED",
                "REJECTED",
                "INVALIDATED",
                "SKIPPED",
                "NOT_EXECUTED",
                "NOT_AVAILABLE",
                "HOLDOUT_LOCKED",
                name="result_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("source_artifact", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["family_id"], ["strategy_families.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["round_id"], ["experiment_rounds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "round_id", "family_id", "symbol", "criterion_key", name="uq_gate_results_natural_key"
        ),
    )
    with op.batch_alter_table("gate_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_gate_results_family_id"), ["family_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_gate_results_round_id"), ["round_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_gate_results_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_gate_results_symbol"), ["symbol"], unique=False)
        batch_op.create_index("ix_gate_results_verdict", ["verdict"], unique=False)

    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("round_id", sa.Integer(), nullable=True),
        sa.Column("family_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("engine", sa.String(length=32), nullable=False),
        sa.Column("run_dir", sa.Text(), nullable=False),
        sa.Column("identity_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config", JSON_VARIANT, nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "EXECUTED",
                "AUDITED",
                "REJECTED",
                "INVALIDATED",
                "SKIPPED",
                "NOT_EXECUTED",
                "NOT_AVAILABLE",
                "HOLDOUT_LOCKED",
                name="result_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("source_artifact", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["family_id"], ["strategy_families.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["round_id"], ["experiment_rounds.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", name="uq_runs_run_id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_engine"), ["engine"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_family_id"), ["family_id"], unique=False)
        batch_op.create_index(
            "ix_runs_family_symbol_engine", ["family_id", "symbol", "engine"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_runs_identity_fingerprint"), ["identity_fingerprint"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_runs_round_id"), ["round_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_study_id"), ["study_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_symbol"), ["symbol"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_timeframe"), ["timeframe"], unique=False)

    op.create_table(
        "strategy_specs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("spec_hash", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=True),
        sa.Column("timeframe", sa.String(length=8), nullable=True),
        sa.Column("params", JSON_VARIANT, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_artifact", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["family_id"], ["strategy_families.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_id", "spec_hash", name="uq_strategy_specs_family_hash"),
    )
    with op.batch_alter_table("strategy_specs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_strategy_specs_family_id"), ["family_id"], unique=False
        )
        batch_op.create_index(
            "ix_strategy_specs_symbol_timeframe", ["symbol", "timeframe"], unique=False
        )

    op.create_table(
        "artifacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uri", sa.Text(), nullable=False),
        sa.Column("backend", sa.String(length=32), nullable=False),
        sa.Column("bucket", sa.String(length=128), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("media_type", sa.String(length=64), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("row_count", sa.BigInteger(), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("arrow_schema", JSON_VARIANT, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("study_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "EXECUTED",
                "AUDITED",
                "REJECTED",
                "INVALIDATED",
                "SKIPPED",
                "NOT_EXECUTED",
                "NOT_AVAILABLE",
                "HOLDOUT_LOCKED",
                name="result_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("source_artifact", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("backend", "bucket", "object_key", name="uq_artifacts_location"),
        sa.UniqueConstraint("uri", name="uq_artifacts_uri"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_artifacts_content_sha256"), ["content_sha256"], unique=False
        )
        batch_op.create_index("ix_artifacts_kind", ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_study_id"), ["study_id"], unique=False)

    op.create_table(
        "folds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("fold_index", sa.Integer(), nullable=False),
        sa.Column("train_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("train_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("test_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("test_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("purge_bars", sa.Integer(), nullable=True),
        sa.Column("embargo_bars", sa.Integer(), nullable=True),
        sa.Column("n_train_bars", sa.Integer(), nullable=True),
        sa.Column("n_test_bars", sa.Integer(), nullable=True),
        sa.Column("source_artifact", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "fold_index", name="uq_folds_run_index"),
    )
    with op.batch_alter_table("folds", schema=None) as batch_op:
        batch_op.create_index("ix_folds_fold_index", ["fold_index"], unique=False)
        batch_op.create_index(batch_op.f("ix_folds_run_id"), ["run_id"], unique=False)

    op.create_table(
        "run_seeds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("n_folds", sa.Integer(), nullable=True),
        sa.Column("n_bars", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "EXECUTED",
                "AUDITED",
                "REJECTED",
                "INVALIDATED",
                "SKIPPED",
                "NOT_EXECUTED",
                "NOT_AVAILABLE",
                "HOLDOUT_LOCKED",
                name="result_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("total_return", sa.Double(), nullable=True),
        sa.Column("sharpe", sa.Double(), nullable=True),
        sa.Column("sortino", sa.Double(), nullable=True),
        sa.Column("max_drawdown", sa.Double(), nullable=True),
        sa.Column("calmar", sa.Double(), nullable=True),
        sa.Column("profit_factor", sa.Double(), nullable=True),
        sa.Column("win_rate", sa.Double(), nullable=True),
        sa.Column("n_trades", sa.Integer(), nullable=True),
        sa.Column("turnover", sa.Double(), nullable=True),
        sa.Column("exposure", sa.Double(), nullable=True),
        sa.Column("costs", sa.Double(), nullable=True),
        sa.Column("funding", sa.Double(), nullable=True),
        sa.Column("source_artifact", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "seed", name="uq_run_seeds_run_seed"),
    )
    with op.batch_alter_table("run_seeds", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_seeds_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_run_seeds_seed"), ["seed"], unique=False)
        batch_op.create_index(batch_op.f("ix_run_seeds_status"), ["status"], unique=False)

    op.create_table(
        "search_evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("fold_index", sa.Integer(), nullable=False),
        sa.Column("evaluation_index", sa.Integer(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=True),
        sa.Column("spec_id", sa.Integer(), nullable=True),
        sa.Column("objective", sa.Double(), nullable=True),
        sa.Column("objective_name", sa.String(length=64), nullable=True),
        sa.Column("feasible", sa.Boolean(), nullable=True),
        sa.Column("params", JSON_VARIANT, nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "EXECUTED",
                "AUDITED",
                "REJECTED",
                "INVALIDATED",
                "SKIPPED",
                "NOT_EXECUTED",
                "NOT_AVAILABLE",
                "HOLDOUT_LOCKED",
                name="result_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("source_artifact", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["spec_id"], ["strategy_specs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id",
            "seed",
            "fold_index",
            "evaluation_index",
            name="uq_search_evaluations_natural_key",
        ),
    )
    with op.batch_alter_table("search_evaluations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_search_evaluations_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            "ix_search_evaluations_run_seed_fold", ["run_id", "seed", "fold_index"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_search_evaluations_spec_id"), ["spec_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_search_evaluations_status"), ["status"], unique=False)

    op.create_table(
        "fold_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fold_id", sa.Integer(), nullable=False),
        sa.Column("run_seed_id", sa.Integer(), nullable=False),
        sa.Column("spec_id", sa.Integer(), nullable=True),
        sa.Column("is_train", sa.Boolean(), nullable=False),
        sa.Column("params", JSON_VARIANT, nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "EXECUTED",
                "AUDITED",
                "REJECTED",
                "INVALIDATED",
                "SKIPPED",
                "NOT_EXECUTED",
                "NOT_AVAILABLE",
                "HOLDOUT_LOCKED",
                name="result_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("total_return", sa.Double(), nullable=True),
        sa.Column("sharpe", sa.Double(), nullable=True),
        sa.Column("sortino", sa.Double(), nullable=True),
        sa.Column("max_drawdown", sa.Double(), nullable=True),
        sa.Column("calmar", sa.Double(), nullable=True),
        sa.Column("profit_factor", sa.Double(), nullable=True),
        sa.Column("win_rate", sa.Double(), nullable=True),
        sa.Column("n_trades", sa.Integer(), nullable=True),
        sa.Column("turnover", sa.Double(), nullable=True),
        sa.Column("exposure", sa.Double(), nullable=True),
        sa.Column("costs", sa.Double(), nullable=True),
        sa.Column("funding", sa.Double(), nullable=True),
        sa.Column("source_artifact", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["fold_id"], ["folds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_seed_id"], ["run_seeds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["spec_id"], ["strategy_specs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fold_id", "run_seed_id", name="uq_fold_results_fold_seed"),
    )
    with op.batch_alter_table("fold_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fold_results_fold_id"), ["fold_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_fold_results_run_seed_id"), ["run_seed_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_fold_results_spec_id"), ["spec_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_fold_results_status"), ["status"], unique=False)

    op.create_table(
        "monte_carlo_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("method", sa.String(length=48), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("n_paths", sa.Integer(), nullable=False),
        sa.Column("horizon_bars", sa.Integer(), nullable=True),
        sa.Column("block_probability", sa.Double(), nullable=True),
        sa.Column("terminal_p05", sa.Double(), nullable=True),
        sa.Column("terminal_p25", sa.Double(), nullable=True),
        sa.Column("terminal_median", sa.Double(), nullable=True),
        sa.Column("terminal_p75", sa.Double(), nullable=True),
        sa.Column("terminal_p95", sa.Double(), nullable=True),
        sa.Column("prob_positive", sa.Double(), nullable=True),
        sa.Column("mean_max_drawdown", sa.Double(), nullable=True),
        sa.Column("artifact_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "EXECUTED",
                "AUDITED",
                "REJECTED",
                "INVALIDATED",
                "SKIPPED",
                "NOT_EXECUTED",
                "NOT_AVAILABLE",
                "HOLDOUT_LOCKED",
                name="result_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("source_artifact", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["family_id"], ["strategy_families.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "study_id", "family_id", "symbol", "method", "seed", name="uq_monte_carlo_natural_key"
        ),
    )
    with op.batch_alter_table("monte_carlo_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_monte_carlo_runs_artifact_id"), ["artifact_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_monte_carlo_runs_family_id"), ["family_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_monte_carlo_runs_seed"), ["seed"], unique=False)
        batch_op.create_index(batch_op.f("ix_monte_carlo_runs_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_monte_carlo_runs_study_id"), ["study_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_monte_carlo_runs_symbol"), ["symbol"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monte_carlo_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_monte_carlo_runs_symbol"))
        batch_op.drop_index(batch_op.f("ix_monte_carlo_runs_study_id"))
        batch_op.drop_index(batch_op.f("ix_monte_carlo_runs_status"))
        batch_op.drop_index(batch_op.f("ix_monte_carlo_runs_seed"))
        batch_op.drop_index(batch_op.f("ix_monte_carlo_runs_family_id"))
        batch_op.drop_index(batch_op.f("ix_monte_carlo_runs_artifact_id"))

    op.drop_table("monte_carlo_runs")
    with op.batch_alter_table("fold_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fold_results_status"))
        batch_op.drop_index(batch_op.f("ix_fold_results_spec_id"))
        batch_op.drop_index(batch_op.f("ix_fold_results_run_seed_id"))
        batch_op.drop_index(batch_op.f("ix_fold_results_fold_id"))

    op.drop_table("fold_results")
    with op.batch_alter_table("search_evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_evaluations_status"))
        batch_op.drop_index(batch_op.f("ix_search_evaluations_spec_id"))
        batch_op.drop_index("ix_search_evaluations_run_seed_fold")
        batch_op.drop_index(batch_op.f("ix_search_evaluations_run_id"))

    op.drop_table("search_evaluations")
    with op.batch_alter_table("run_seeds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_seeds_status"))
        batch_op.drop_index(batch_op.f("ix_run_seeds_seed"))
        batch_op.drop_index(batch_op.f("ix_run_seeds_run_id"))

    op.drop_table("run_seeds")
    with op.batch_alter_table("folds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_folds_run_id"))
        batch_op.drop_index("ix_folds_fold_index")

    op.drop_table("folds")
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifacts_study_id"))
        batch_op.drop_index(batch_op.f("ix_artifacts_status"))
        batch_op.drop_index(batch_op.f("ix_artifacts_run_id"))
        batch_op.drop_index("ix_artifacts_kind")
        batch_op.drop_index(batch_op.f("ix_artifacts_content_sha256"))

    op.drop_table("artifacts")
    with op.batch_alter_table("strategy_specs", schema=None) as batch_op:
        batch_op.drop_index("ix_strategy_specs_symbol_timeframe")
        batch_op.drop_index(batch_op.f("ix_strategy_specs_family_id"))

    op.drop_table("strategy_specs")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_timeframe"))
        batch_op.drop_index(batch_op.f("ix_runs_symbol"))
        batch_op.drop_index(batch_op.f("ix_runs_study_id"))
        batch_op.drop_index(batch_op.f("ix_runs_status"))
        batch_op.drop_index(batch_op.f("ix_runs_round_id"))
        batch_op.drop_index(batch_op.f("ix_runs_identity_fingerprint"))
        batch_op.drop_index("ix_runs_family_symbol_engine")
        batch_op.drop_index(batch_op.f("ix_runs_family_id"))
        batch_op.drop_index(batch_op.f("ix_runs_engine"))

    op.drop_table("runs")
    with op.batch_alter_table("gate_results", schema=None) as batch_op:
        batch_op.drop_index("ix_gate_results_verdict")
        batch_op.drop_index(batch_op.f("ix_gate_results_symbol"))
        batch_op.drop_index(batch_op.f("ix_gate_results_status"))
        batch_op.drop_index(batch_op.f("ix_gate_results_round_id"))
        batch_op.drop_index(batch_op.f("ix_gate_results_family_id"))

    op.drop_table("gate_results")
    with op.batch_alter_table("strategy_families", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategy_families_study_id"))
        batch_op.drop_index(batch_op.f("ix_strategy_families_status"))
        batch_op.drop_index("ix_strategy_families_key")

    op.drop_table("strategy_families")
    with op.batch_alter_table("metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metrics_study_id"))
        batch_op.drop_index(batch_op.f("ix_metrics_status"))
        batch_op.drop_index(batch_op.f("ix_metrics_scope_ref"))
        batch_op.drop_index(batch_op.f("ix_metrics_scope"))
        batch_op.drop_index("ix_metrics_key")

    op.drop_table("metrics")
    with op.batch_alter_table("holdout_registry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_holdout_registry_study_id"))
        batch_op.drop_index(batch_op.f("ix_holdout_registry_status"))

    op.drop_table("holdout_registry")
    with op.batch_alter_table("experiment_rounds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_experiment_rounds_study_id"))
        batch_op.drop_index(batch_op.f("ix_experiment_rounds_status"))
        batch_op.drop_index("ix_experiment_rounds_key")

    op.drop_table("experiment_rounds")
    op.drop_table("studies")
    # ### end Alembic commands ###
