"""Generate the pilot search configurations, one per preregistered family.

The pilot exists to prove the pipeline, not to find a strategy. It therefore
keeps everything that affects comparability fixed -- geometry, costs, execution,
fitness, holdout boundary -- and reduces only the evaluation budget. Reducing the
number of folds or assets instead would test a different experiment from the one
that will actually be run.

Every family gets the SAME effective budget, so a family that happens to be
cheaper to evaluate does not quietly receive more search.
"""

from __future__ import annotations

from pathlib import Path

# Preregistered families for the pilot: the frozen baseline plus the three new
# ones. Listed here so the pilot cannot silently drop a family.
FAMILIES = ("momentum", "volatility_breakout", "funding", "BTC_ETH_confirmation")

# Reduced but fixed. Both engines must land on exactly this number of unique,
# valid, non-cached evaluations.
PILOT_BUDGET = 60

TEMPLATE = """\
# =====================================================================
# PILOT walk-forward search -- family: {family}
#
# Generated by scripts/make_pilot_configs.py. Do not hand-edit: regenerate.
#
# Purpose: prove that the whole pipeline runs for this family across the full
# development geometry. It is NOT a research result. The budget is deliberately
# small, so the winning parameters carry no evidential weight.
#
# Held fixed across every pilot family (this is the point of the pilot):
#   * 15 walk-forward folds over development = [2020-01-01, 2026-01-01)
#   * geometry 730d train / 90d validation / 90d test / 90d step
#   * costs, execution timing, fitness and annualisation from experiment.yaml
#   * effective_budget = {budget}, spent exactly by BOTH Random Search and the GA
#
# The frozen holdout [2026-01-01, 2026-07-01) is never loaded.
#
# EXPLORATORY PIPELINE CHECK -- not development evidence, not holdout evidence.
# =====================================================================

experiment_config: configs/experiment.yaml
data_contract: configs/data_contract.yaml

family: {family}
algorithm: comparison
symbol: BTCUSDT
timeframe: "1h"
seed: 42
regime_model: threshold

require_funding: true
synthetic: false
label: pilot_{family}_EXPLORATORY_not_holdout

effective_budget: {budget}

ga:
  population_size: 20
  max_generations: 40
  crossover_rate: 0.7
  mutation_rate: 0.2
  elitism: 2
  tournament_size: 3
"""


def main() -> int:
    out_dir = Path("configs")
    for family in FAMILIES:
        path = out_dir / f"search_pilot_{family}.yaml"
        path.write_text(TEMPLATE.format(family=family, budget=PILOT_BUDGET), encoding="utf-8")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
