"""Generate the Gate S1-B development pilot configurations, one per S1 family.

S1-B asks a single question: does any of the four pre-specified S1 families show
enough of a development-period signal to justify spending a full budget on it?
It is therefore a *screen*, not a study. Everything that affects comparability is
held fixed at the values Gate R3 already used -- assets, timeframe, walk-forward
geometry, costs, execution timing, objective, seed and the frozen holdout
boundary -- and only the evaluation budget is reduced. Cutting folds or assets
instead would screen a different experiment from the one that would follow.

Every family gets the SAME effective budget, so a family that happens to be
cheaper to evaluate does not quietly receive more search, and both engines spend
that budget exactly.

Regenerate with `uv run python scripts/make_s1_pilot_configs.py`.
"""

from __future__ import annotations

from pathlib import Path

from perp_lab.search.registry import S1_FAMILIES

# Fixed by the Gate S1-B contract: 25 unique, valid, non-cached evaluations per
# fold and per engine. The smallest S1 family still offers 864 distinct
# candidates, so 25 is a genuine screen and never an exhaustive enumeration that
# would let one family search its whole space while another samples a corner.
PILOT_BUDGET = 25

# Sized so the genetic algorithm actually evolves inside the budget: generation 0
# spends 10 evaluations and every later generation adds at most 9, so the budget
# is reached during the third generation. A larger population would spend the
# whole budget on an essentially random first generation and reduce the GA to a
# more expensive random search.
GA_POPULATION = 10
GA_ELITISM = 1

TEMPLATE = """\
# =====================================================================
# GATE S1-B DEVELOPMENT PILOT -- family: {family}
#
# Generated by scripts/make_s1_pilot_configs.py. Do not hand-edit: regenerate.
#
# Purpose: screen the four pre-specified S1 families on development data at a
# small, identical budget, to decide which (if any) deserves a full S1-C study.
# It is DEVELOPMENT-PERIOD EVIDENCE ONLY. It is not a promotion decision, and a
# winner here carries no evidential weight on its own.
#
# Held fixed across every S1-B family (this is the point of the screen):
#   * BTCUSDT, 1h primary timeframe
#   * the full development walk-forward geometry from experiment.yaml
#   * costs, execution timing, fitness and annualisation from experiment.yaml
#   * base seed 42
#   * effective_budget = {budget}, spent exactly by BOTH Random Search and the GA
#
# The frozen holdout [2026-01-01, 2026-07-01) is never loaded.
#
# DEV-ONLY SCREEN -- not a promotion decision, not holdout evidence.
# =====================================================================

experiment_config: configs/experiment.yaml
data_contract: configs/data_contract.yaml

family: {family}
algorithm: comparison
symbol: BTCUSDT
timeframe: "1h"
seed: 42
regime_model: threshold

require_funding: true
synthetic: false
label: s1b_pilot_{family}_DEV_ONLY_not_holdout

# Unique, valid, non-cached evaluations spent by EVERY engine in EVERY fold.
effective_budget: {budget}

ga:
  population_size: {population}
  # Safety cap only: execution stops as soon as effective_budget is reached.
  max_generations: 200
  crossover_rate: 0.7
  mutation_rate: 0.2
  elitism: {elitism}
  tournament_size: 3
"""


def main() -> int:
    out_dir = Path("configs")
    for family in S1_FAMILIES:
        path = out_dir / f"search_s1_pilot_{family}.yaml"
        path.write_text(
            TEMPLATE.format(
                family=family,
                budget=PILOT_BUDGET,
                population=GA_POPULATION,
                elitism=GA_ELITISM,
            ),
            encoding="utf-8",
        )
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
