"""Generate the Gate S1-C full-study configurations, one per S1 family.

Mirrors ``make_r3_configs.py`` so the two gates are comparable: same assets, same
walk-forward geometry, same costs and objective, same seed schedule and the same
per-fold effective budget of 100. The family name is again the only experimental
dimension that changes.

Every mechanically viable family gets a config. Which families those are was
decided by the S1-B viability screen, and S1-B is explicitly forbidden from
dropping a family for weak performance (gate_s1_batch_01.md section 3), so the
S1-B performance numbers do not influence this generator at all -- exactly as
pilot metrics did not influence the R3 generator.

**These configs are not executed here.** Starting S1-C is a human decision.

    uv run python scripts/make_s1c_configs.py
"""

from __future__ import annotations

from pathlib import Path

from perp_lab.search.registry import S1_FAMILIES

# Identical to Gate R3 (ADR 0014), so an S1 family and an R3 family are compared
# at the same search intensity rather than at whichever budget suited each.
EFFECTIVE_BUDGET = 100

TEMPLATE = """\
# =====================================================================
# GATE S1-C FULL MULTI-SEED STUDY -- family: {family}
#
# Frozen contract (identical to Gate R3 so the two gates are comparable):
#   * BTCUSDT + ETHUSDT
#   * 10 seeds derived from base seed 42
#   * 15 chronological outer folds over development data
#   * independent search per fold; winner frozen before test
#   * effective_budget = {budget} per fold and engine
#   * Random Search is confirmatory; the GA is a secondary diagnostic
#
# This is development-period evidence, never final-holdout evidence.
# The frozen holdout [2026-01-01, 2026-07-01) is NEVER loaded.
#
# NOT YET EXECUTED. Starting S1-C is a human decision.
#
# Generated by scripts/make_s1c_configs.py. Do not hand-edit.
# =====================================================================

experiment_config: configs/experiment.yaml
data_contract: configs/data_contract.yaml

family: {family}
algorithm: comparison
symbol: BTCUSDT
timeframe: "1h"
seed: 42
regime_model: threshold

require_funding: true
synthetic: false
label: s1c_{family}_full_multiseed_DEV_ONLY_not_holdout

# Unique, valid, non-cached evaluations spent by EVERY engine in EVERY fold.
effective_budget: {budget}

ga:
  population_size: 30
  # Safety cap only; search stops immediately when effective_budget is reached.
  max_generations: 200
  crossover_rate: 0.7
  mutation_rate: 0.2
  elitism: 3
  tournament_size: 3
"""


def main() -> int:
    out_dir = Path("configs")
    for family in S1_FAMILIES:
        path = out_dir / f"search_s1c_{family}.yaml"
        path.write_text(
            TEMPLATE.format(family=family, budget=EFFECTIVE_BUDGET),
            encoding="utf-8",
        )
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
