"""Generate the frozen full-budget configurations for Gate R3.

Every family receives the same data, geometry, seeds, objective, costs and
per-fold effective budget. The family name is the only experimental dimension
that changes. Pilot metrics are deliberately absent from this generator, so they
cannot influence ordering, budget or configuration.
"""

from __future__ import annotations

from pathlib import Path

FAMILIES = (
    "breakout",
    "mean_reversion",
    "volatility_breakout",
    "funding",
    "BTC_ETH_confirmation",
)

# Breakout has exactly 108 unique valid candidate identities after conditional
# parameters are collapsed. A common budget of 100 is the largest round target
# that leaves both stochastic engines headroom to reach parity without requiring
# coupon-collector exhaustion of the smallest space (ADR 0014).
EFFECTIVE_BUDGET = 100

TEMPLATE = """\
# =====================================================================
# R3 FULL MULTI-SEED STUDY -- family: {family}
#
# Frozen contract:
#   * BTCUSDT + ETHUSDT
#   * 10 seeds derived from base seed 42
#   * 15 chronological outer folds over development data
#   * independent search per fold; winner frozen before test
#   * effective_budget = {budget} per fold and engine
#
# This is development-period evidence, never final-holdout evidence.
# The frozen holdout [2026-01-01, 2026-07-01) is NEVER loaded.
#
# Generated by scripts/make_r3_configs.py. Do not hand-edit.
# =====================================================================

experiment_config: configs/experiment.yaml
data_contract: configs/data_contract.yaml

family: {family}
algorithm: comparison
symbol: BTCUSDT
timeframe: "1h"
seed: 42
regime_model: threshold

require_funding: true
synthetic: false
label: r3_{family}_full_multiseed_EXPLORATORY_not_holdout

# Unique, valid, non-cached evaluations spent by EVERY engine in EVERY fold.
effective_budget: {budget}

ga:
  population_size: 30
  # Safety cap only; search stops immediately when effective_budget is reached.
  max_generations: 200
  crossover_rate: 0.7
  mutation_rate: 0.2
  elitism: 3
  tournament_size: 3
"""


def main() -> int:
    out_dir = Path("configs")
    for family in FAMILIES:
        path = out_dir / f"search_r3_{family}.yaml"
        path.write_text(
            TEMPLATE.format(family=family, budget=EFFECTIVE_BUDGET),
            encoding="utf-8",
        )
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
