"""Generate the round ``CRT_INTRADAY_V1`` configurations, one per CRT family.

Mirrors ``make_r3_configs.py`` and ``make_s1c_configs.py`` so a CRT family is
compared against an R3 or S1 family at the same search intensity rather than at
whichever budget happened to suit it: same assets, same walk-forward geometry,
same costs and objective, same seed schedule, same per-fold effective budget of
100. The family name remains the only experimental dimension that changes.

Order matters here. ``pdl_reclaim_long`` and its mirror ``pdh_reclaim_short``
are emitted first because they are the pair the round opens with: they share one
mechanism read in two directions, so running them together is also the cheapest
available check that the engine is not accidentally direction-biased.

The parameter ranges are **not** defined here. They live frozen in
``search/registry.py`` under ``SPACE_VERSION`` and are pre-registered in
``docs/methodology/crt_intraday.md``; this script only fixes the protocol around
them. Nothing in this file may be tuned after seeing a result.

**These configs are not executed here.** Starting the round is a human decision.

    uv run python scripts/make_crt_configs.py
"""

from __future__ import annotations

from pathlib import Path

from perp_lab.search.registry import CRT_INTRADAY_V1_FAMILIES

# Identical to Gate R3 (ADR 0014) and to Gate S1-C.
EFFECTIVE_BUDGET = 100

# The round opens on the long/short mirror pair; the remaining families follow
# in registry order. Emission order does not affect any result — it only makes
# the intended execution order explicit and reproducible.
OPENING_PAIR = ("pdl_reclaim_long", "pdh_reclaim_short")

TEMPLATE = """\
# =====================================================================
# ROUND CRT_INTRADAY_V1 FULL MULTI-SEED STUDY -- family: {family}
#
# Frozen contract (identical to Gate R3 and Gate S1-C so the rounds are
# comparable):
#   * BTCUSDT + ETHUSDT
#   * 10 seeds derived from base seed 42
#   * 15 chronological outer folds over development data
#   * independent search per fold; winner frozen before test
#   * effective_budget = {budget} per fold and engine
#   * Random Search is confirmatory; the GA is a secondary robustness
#     cross-check and never the primary evidence
#
# Parameter ranges are frozen in search/registry.py (SPACE_VERSION) and
# pre-registered in docs/methodology/crt_intraday.md. They must not be adjusted
# after observing any result from this round.
#
# This is development-period evidence. The reserved partition
# [2026-01-01, 2026-07-01) is NEVER loaded by this config, and is in any case
# already consumed -- see docs/methodology/holdout_audit_status.md. No family in
# this round can obtain a confirmatory test on this dataset.
#
# Every configuration evaluated under this round counts toward the study-level
# multiple-testing denominator. Reporting any number from here REQUIRES
# re-running scripts/run_study_closure.py first: the current correction is fixed
# at N = 13 families and does not include this round.
#
# NOT YET EXECUTED. Starting this round is a human decision.
#
# Generated by scripts/make_crt_configs.py. Do not hand-edit.
# =====================================================================

experiment_config: configs/experiment.yaml
data_contract: configs/data_contract.yaml

family: {family}
algorithm: comparison
symbol: BTCUSDT
timeframe: "1h"
seed: 42
regime_model: threshold

require_funding: true
synthetic: false
label: crt_v1_{family}_full_multiseed_DEV_ONLY_not_holdout

# Unique, valid, non-cached evaluations spent by EVERY engine in EVERY fold.
effective_budget: {budget}

ga:
  population_size: 30
  # Safety cap only; search stops immediately when effective_budget is reached.
  max_generations: 200
  crossover_rate: 0.7
  mutation_rate: 0.2
  elitism: 3
  tournament_size: 3
"""


def ordered_families() -> tuple[str, ...]:
    """Opening mirror pair first, then the rest in registry order."""
    rest = tuple(f for f in CRT_INTRADAY_V1_FAMILIES if f not in OPENING_PAIR)
    missing = tuple(f for f in OPENING_PAIR if f not in CRT_INTRADAY_V1_FAMILIES)
    if missing:
        raise ValueError(f"Opening pair not registered in the round: {missing}")
    return (*OPENING_PAIR, *rest)


def main() -> int:
    out_dir = Path("configs")
    for family in ordered_families():
        path = out_dir / f"search_crt_v1_{family}.yaml"
        path.write_text(
            TEMPLATE.format(family=family, budget=EFFECTIVE_BUDGET),
            encoding="utf-8",
        )
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
