"""Generate the Gate S2-B development pilot configurations.

One config per (family, asset, seed) as frozen in
``docs/roadmap/gate_s2_batch_01.md`` section 8: three families, both assets, and
seeds {42, 43, 44}, all at the same per-fold budget S1-B used so the unit of
search stays comparable across batches.

Everything that affects comparability is held fixed at the values Gate R3 and
Gate S1-B already used -- timeframe, walk-forward geometry, costs, execution
timing, objective and the frozen holdout boundary -- and only the family, asset
and seed vary. Every family gets the SAME effective budget, so a family that
happens to be cheaper to evaluate does not quietly receive more search, and both
engines spend that budget exactly.

Regenerate with `uv run python scripts/make_s2_pilot_configs.py`.
"""

from __future__ import annotations

from pathlib import Path

from perp_lab.search.registry import S2_FAMILIES

# Frozen by the Gate S2-B contract, identical to S1-B: 25 unique, valid,
# non-cached evaluations per fold and per engine. The smallest S2 family still
# offers 5 184 distinct candidates, so 25 is a genuine screen and never an
# exhaustive enumeration that would let one family search its whole space while
# another samples a corner.
PILOT_BUDGET = 25

# Sized so the genetic algorithm actually evolves inside the budget: generation 0
# spends 10 evaluations and every later generation adds at most 9, so the budget
# is reached during the third generation.
GA_POPULATION = 10
GA_ELITISM = 1

SYMBOLS = ("BTCUSDT", "ETHUSDT")
SEEDS = (42, 43, 44)

TEMPLATE = """\
# =====================================================================
# GATE S2-B DEVELOPMENT PILOT -- family: {family} | {symbol} | seed {seed}
#
# Generated by scripts/make_s2_pilot_configs.py. Do not hand-edit: regenerate.
#
# Purpose: screen the three pre-specified S2 order-flow families on development
# data at a small, identical budget, to decide which (if any) deserves a full
# S2-C study. It is DEVELOPMENT-PERIOD EVIDENCE ONLY. It is not a promotion
# decision, and a winner here carries no evidential weight on its own.
#
# Held fixed across every S2-B run (this is the point of the screen):
#   * 1h primary timeframe
#   * the full development walk-forward geometry from experiment.yaml
#   * costs, execution timing, fitness and annualisation from experiment.yaml
#   * effective_budget = {budget}, spent exactly by BOTH Random Search and the GA
#
# Varying, and reported separately: family, asset, seed, engine, fold.
#
# The frozen holdout [2026-01-01, 2026-07-01) is never loaded.
#
# DEV-ONLY SCREEN -- not a promotion decision, not holdout evidence.
# =====================================================================

experiment_config: configs/experiment.yaml
data_contract: configs/data_contract.yaml

family: {family}
algorithm: comparison
symbol: {symbol}
timeframe: "1h"
seed: {seed}
regime_model: threshold

# Funding is a cashflow on every held position at this holding horizon, so it is
# required rather than optional: a multi-hour family that ignored it would be
# reporting a return it could not have earned.
require_funding: true
synthetic: false
label: s2b_pilot_{family}_{symbol}_seed{seed}_DEV_ONLY_not_holdout

# Unique, valid, non-cached evaluations spent by EVERY engine in EVERY fold.
effective_budget: {budget}

ga:
  population_size: {population}
  # Safety cap only: execution stops as soon as effective_budget is reached.
  max_generations: 200
  crossover_rate: 0.7
  mutation_rate: 0.2
  elitism: {elitism}
  tournament_size: 3
"""


def main() -> int:
    out_dir = Path("configs")
    written = 0
    for family in S2_FAMILIES:
        for symbol in SYMBOLS:
            for seed in SEEDS:
                path = out_dir / f"search_s2_pilot_{family}_{symbol}_seed{seed}.yaml"
                path.write_text(
                    TEMPLATE.format(
                        family=family,
                        symbol=symbol,
                        seed=seed,
                        budget=PILOT_BUDGET,
                        population=GA_POPULATION,
                        elitism=GA_ELITISM,
                    ),
                    encoding="utf-8",
                )
                written += 1
    print(f"wrote {written} S2-B pilot configs to {out_dir}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
