"""Piece 2 of the study closure: EXPLORATORY regime-conditioned re-analysis.

Reads persisted development-partition artifacts and development market data.
Never opens the holdout. Promotes nothing.

    uv run python scripts/run_regime_conditioned.py
"""

from __future__ import annotations

import argparse
import json
import logging
import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from perp_lab.config.settings import load_data_contract, load_settings
from perp_lab.eda.datasets import DataLake
from perp_lab.reporting.regime_conditioned import (
    MIN_CELL_BARS,
    best_conditional_candidate,
    causal_trend_labels,
    correct_within_block,
    family_regime_series,
    regime_cells,
)
from perp_lab.reporting.study_closure import PRIMARY_ENGINE, PRIMARY_SYMBOL, build_inventory

log = logging.getLogger("regime_conditioned")

EXPLORATORY_BANNER = (
    "> **EXPLORATORY — NOT A VALIDATED RESULT.** Everything below is a hypothesis "
    "generated by slicing records the study already rejected. Nothing here is "
    "promoted, and no cell may be treated as a strategy without independent "
    "confirmation on data it never touched."
)


def _markdown(payload: dict[str, Any]) -> str:
    correction = payload["correction"]
    lines: list[str] = []
    add = lines.append

    add("# Regime-conditioned re-analysis of the rejected families")
    add("")
    add(f"**Generated:** {payload['generated_at']} · **Commit:** `{payload['git_commit']}`")
    add(f"**Partition:** development only · **Holdout accessed:** {payload['holdout_accessed']}")
    add("")
    add(EXPLORATORY_BANNER)
    add("")
    add(
        "The gates judged each family on its whole out-of-sample record. This asks "
        "one further question of the same records: was there an effect in only part "
        "of the state space? No family is added, no parameter is changed."
    )
    add("")

    add("## Method")
    add("")
    add(
        "**Volatility regimes** are the `regime` labels already carried by the "
        "persisted ledgers, produced by a threshold model fitted on each fold's "
        "training slice only. They are causal by construction."
    )
    add("")
    add(
        "**Trend regimes** come from `eda.regimes.tag_trend_volatility_regimes`, of "
        "which only the `trend_regime` output is used: price against its own "
        "trailing moving average, which looks strictly backwards. That function's "
        "volatility buckets use full-sample quantiles and are deliberately **not** "
        "used, because a slice defined with future information must never inform a "
        "candidate for the holdout."
    )
    add("")
    add(
        f"Cells with fewer than {MIN_CELL_BARS} bars are reported but excluded from "
        "the corrected family: too small to support a claim either way."
    )
    add("")
    add(
        "**The block is corrected within itself.** Conditioning multiplies the "
        "tests, and correcting inside the block is what stops the slicing from "
        "producing the discovery it was designed to look for. This count is kept "
        "separate from the study-level count, which answered a different question."
    )
    add("")

    add("## Results by family and state")
    add("")
    add(
        "| Family | Gate | Dimension | Regime | Bars | Share | Total return | Sharpe (ann.) | p | p BH |"
    )
    add("|---|---|---|---|---:|---:|---:|---:|---:|---:|")
    bh_adj = correction["benjamini_hochberg"]["adjusted_p_values"]
    for cell in payload["cells"]:
        label = f"{cell['family']}|{cell['dimension']}|{cell['regime']}"
        raw = "—" if cell["p_value"] is None else f"{cell['p_value']:.3f}"
        adj = f"{bh_adj[label]:.3f}" if label in bh_adj else "—"
        add(
            f"| `{cell['family']}` | {cell['gate']} | {cell['dimension']} | "
            f"{cell['regime']} | {cell['n_bars']:,} | {cell['share_of_bars']:.0%} | "
            f"{cell['total_return']:+.1%} | {cell['sharpe_annualised']:+.2f} | {raw} | {adj} |"
        )
    add("")

    add("## Did anything survive?")
    add("")
    add(
        f"Cells examined: **{correction['n_cells']}**, of which "
        f"{correction['n_testable_cells']} were large enough to test "
        f"({correction['n_excluded_small_cells']} excluded as too small)."
    )
    add("")
    add(
        f"Surviving Holm within the block: **{correction['holm_bonferroni']['n_rejected']}**. "
        f"Surviving Benjamini-Hochberg: **{correction['benjamini_hochberg']['n_rejected']}**."
    )
    add("")
    if payload["candidate"]:
        candidate = payload["candidate"]
        add(
            f"The strongest surviving cell is **`{candidate['label']}`** "
            f"(adjusted p = {candidate['adjusted_p_value']:.3f}, "
            f"Sharpe {candidate['sharpe_annualised']:+.2f} over "
            f"{candidate['n_bars']:,} bars). It is a **generated hypothesis**: it was "
            "found by conditioning a rejected record, not by a pre-registered test, "
            "and it carries no promotion."
        )
    else:
        add(
            "**No cell survives correction within the block.** Conditioning the "
            "rejected families on market state does not recover an effect in any "
            "part of the state space examined."
        )
    add("")

    add("## Conclusion")
    add("")
    add(payload["conclusion"])
    add("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path())
    parser.add_argument("--output-dir", type=Path, default=Path("reports/study_closure"))
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    root: Path = args.root.resolve()

    units = build_inventory(root)
    gates = {u.family: u.gate for u in units}
    series = family_regime_series(units, symbol=PRIMARY_SYMBOL, engine=PRIMARY_ENGINE)
    log.info("Regime-tagged series for %d families", len(series))

    settings = load_settings()
    contract = load_data_contract(Path("configs/data_contract.yaml"))
    lake = DataLake(contract, settings.paths)
    loaded = lake.load_klines(PRIMARY_SYMBOL, "1h", partition="development")
    log.info("Development bars for the trend tag: %d (holdout excluded)", loaded.frame.height)
    trend = causal_trend_labels(loaded.frame.select("open_time", "close"))

    cells = regime_cells(series, gates, trend=trend)
    log.info("Built %d family-by-regime cells", len(cells))
    correction = correct_within_block(cells)
    candidate = best_conditional_candidate(cells, correction)

    if candidate is None:
        conclusion = (
            f"Across {correction['n_testable_cells']} testable family-by-regime cells, "
            "no cell survives multiple-testing correction within this exploratory "
            "block. The rejected families do not conceal an effect confined to high "
            "or low volatility, or to trending or ranging markets. The negative "
            "result is not an artefact of averaging across market states."
        )
    else:
        conclusion = (
            f"One cell, `{candidate['label']}`, survives correction within this "
            f"exploratory block (adjusted p = {candidate['adjusted_p_value']:.3f}). It "
            "is a generated hypothesis requiring independent confirmation, not a "
            "strategy, and it was found by conditioning a record that was already "
            "rejected."
        )

    commit = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=root, capture_output=True, text=True
    ).stdout.strip()

    payload: dict[str, Any] = {
        "report": "regime_conditioned_evaluation",
        "status": "EXPLORATORY - generated hypotheses only, nothing promoted",
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "git_commit": commit,
        "holdout_accessed": False,
        "symbol": PRIMARY_SYMBOL,
        "engine": PRIMARY_ENGINE,
        "cells": [c.to_dict() for c in cells],
        "correction": correction,
        "candidate": candidate,
        "conclusion": conclusion,
    }

    out: Path = args.output_dir
    out.mkdir(parents=True, exist_ok=True)
    (out / "regime_conditioned.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    (out / "regime_conditioned.md").write_text(_markdown(payload), encoding="utf-8")
    log.info("Wrote %s", out / "regime_conditioned.md")

    print(conclusion)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
