"""Reproducible run records: the local artifact contract before MLflow.

Each pipeline run writes a self-describing folder ``artifacts/runs/<run_id>/``
tying together the resolved configuration, dataset hashes, git state, the
environment, the seed, metrics, feature metadata, trades and the equity curve.
The folder is git-ignored (heavy, regenerated by the pipeline).
"""

from perp_lab.tracking.run import (
    RunTracker,
    environment_info,
    generate_run_id,
    git_state,
)

__all__ = ["RunTracker", "environment_info", "generate_run_id", "git_state"]
